blank_issues_enabled: true
contact_links:
  - name: Self-serve Request
    url: https://github.com/multiformats/github-mgmt/edit/master/github/multiformats.yml
    about: Propose a GitHub configuration change by modifying multiformats.yml
